// <auto-generated />
using System;
using Desafio_Fast.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Fast.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918235352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio_Fast.Models.Ata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Atas");
                });

            modelBuilder.Entity("Desafio_Fast.Models.AtaColaborador", b =>
                {
                    b.Property<int>("AtaId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.HasKey("AtaId", "ColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("AtaColaboradores");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DataRealizacao");

                    b.HasIndex("Nome");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Ata", b =>
                {
                    b.HasOne("Desafio_Fast.Models.Workshop", "Workshop")
                        .WithMany("Atas")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Desafio_Fast.Models.AtaColaborador", b =>
                {
                    b.HasOne("Desafio_Fast.Models.Ata", "Ata")
                        .WithMany("AtaColaboradores")
                        .HasForeignKey("AtaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Desafio_Fast.Models.Colaborador", "Colaborador")
                        .WithMany("AtaColaboradores")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ata");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Ata", b =>
                {
                    b.Navigation("AtaColaboradores");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Colaborador", b =>
                {
                    b.Navigation("AtaColaboradores");
                });

            modelBuilder.Entity("Desafio_Fast.Models.Workshop", b =>
                {
                    b.Navigation("Atas");
                });
#pragma warning restore 612, 618
        }
    }
}
